name = "policy-gateway-vm-mod-worker"
main = "index.js"
compatibility_date = "2025-07-01"

# vm-mod-worker 需要 AUTH_TABLE 和 PENDING_QUEUE 来管理模块
[[kv_namespaces]]
binding = "AUTH_TABLE"
id = ""

[[kv_namespaces]]
binding = "PENDING_QUEUE"
id = ""

# 模块注册表存储
[[kv_namespaces]]
binding = "MODULE_REGISTRY"
id = ""
